// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjtxWBjl5owdaX6M6RKTyrtXaxRRSB0hA',
    appId: '1:682814163678:web:0329013d1321ba38f1104f',
    messagingSenderId: '682814163678',
    projectId: 'phone-contact-96b59',
    authDomain: 'phone-contact-96b59.firebaseapp.com',
    storageBucket: 'phone-contact-96b59.appspot.com',
    measurementId: 'G-TPD101XBMS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTbCWpiY_PQiEuM1wQh7r2WalJAMocDJ4',
    appId: '1:682814163678:android:e3ccba6379e54f07f1104f',
    messagingSenderId: '682814163678',
    projectId: 'phone-contact-96b59',
    storageBucket: 'phone-contact-96b59.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjtxWBjl5owdaX6M6RKTyrtXaxRRSB0hA',
    appId: '1:682814163678:web:5592a2f1e8d6351ff1104f',
    messagingSenderId: '682814163678',
    projectId: 'phone-contact-96b59',
    authDomain: 'phone-contact-96b59.firebaseapp.com',
    storageBucket: 'phone-contact-96b59.appspot.com',
    measurementId: 'G-HW15G0RJLK',
  );
}
